### ISSUE TITLE
css 中实现垂直居中的 n 种方式 

### ISSUE THREAD

**Issue by stnhu** [stnhu/blog#2]
如果父元素高度不固定，使用 `padding: 10px 0;` 即可将子元素垂直居中。
如果父元素高度固定，可以使用下面的方式来实现子元素的垂直居中。

这篇文章是讨论在父元素高度固定的情况下，让子元素实现垂直居中。

1. 不推荐将父元素高度写死。
2. 推荐使用副作用/局限性小的写法

# flex 实现垂直居中

利用 `align-item: center` 来实现垂直居中：

```css
.child {
  border: 1px solid green;
  height: 50px;
  width: 200px;
}

.parent {
  border: 1px solid red;
  height: 300px;
  display: flex;
  justify-content: center; /* 水平居中 */
  align-items: center;  /* 垂直居中 */
  /* 下面一句替代上面两句, 实现垂直居中 */
  margin: auto;
}

/*
  <div class="parent">
    <div class="child">子元素</div>
  </div>
*/
```

补充说明：
使用 grid 布局实现垂直居中和 flex 布局方法类似。但一般不用。

```css
.parent {
  border: 1px solid red;
  height: 300px;
  display: gird;
  justify-content: center; /* 水平居中 */
  align-items: center;  /* 垂直居中 */
  jestify-items: center;  /* 替代上面的语句，渲染方式不一样，同样可以实现垂直居中 */
  /* 下面一句替代上面两句, 实现垂直居中 */
  margin: auto;
}

/*
  <div class="parent">
    <div class="child">子元素</div>
  </div>
*/
```

# 绝对定位实现垂直居中

配合 `margin: auto` 这一属性来实现垂直居中：

```css
.parent {
  border: 1px solid red;
  height: 300px;
  position: relative;
}
.child {
  border: 1px solid green;
  height: 50px;
  width: 200px;
  position: absolute;
  margin: auto;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
}

/*
  <div class="parent">
    <div class="child">子元素</div>
  </div>
*/
```

配合 `transform: translate(-50%,-50%)` 这一属性来实现垂直居中：

```css
.parent{
  height: 600px;
  border: 1px solid red;
  position: relative;
}
.child{
  border: 1px solid green;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%,-50%);
}

/*
  <div class="parent">
    <div class="child">子元素</div>
  </div>
*/
```

如果知道 子元素自身的宽高，还可以用下面的方式来实现垂直居中：

```css
.parent{
  height: 600px;
  border: 1px solid red;
  position: relative;
}
.child{
  border: 1px solid green;
  width: 300px;
  position: absolute;
  top: 50%;
  left: 50%;
  margin-left: -150px;
  height: 100px;
  margin-top: -50px;
}

/*
  <div class="parent">
    <div class="child">子元素</div>
  </div>
*/
```

# 利用 table 属性实现垂直居中

```css
wrapper { /* 解决父元素高度塌陷问题 */
  width: 100%;
  display: table;
}
.parent {
  border: 1px solid red;
  height: 300px;
  display: table-cell;
  vertical-align: middle;  /* 可以实现 table 子元素的垂直居中 */
  text-align: center;  /* 可以实现 inline-block 子元素的垂直居中 */
}
.child {
  border: 1px solid green;
  height: 50px;
  width: 200px;
  display: inline-block;
}

/*
  <wrapper>
    <div class="parent">
      <div class="child">子元素</div>
    </div>
  </wrapper>
*/
```

# 利用基线对其实现垂直居中

```css
.parent {
  border: 1px solid red;
  height: 300px;
  text-align: center;
}
.parent::after {
  content: '';
  line-height: 300px;
}

.child {
  border: 1px solid green;
  /*   
  height: 50px;
  width: 200px; 
  */
  display: inline-block;
}
/*
<div class="parent">
  <div class="child">子元素</div>
</div>
*/
```
